### ISSUE TITLE
Can be integrate in Nano?

### ISSUE THREAD

**Issue by drigolin** [friendsofhyperf/trigger#12]
Nice work. I have one question: I see using Annotations can be used without them to use it in Nano?

**Comment by huangdijia** [comment]
It looks like nano doesn't support annotations

**Comment by drigolin** [comment]
Yes, this is the reason of my question. 
Maybe you can add an example of method calls to register subscribers and listeners and do same as Annotations do.

**Comment by huangdijia** [comment]
[https:github.com/orgs/hyperf/discussions/5035](https://github.com/orgs/hyperf/discussions/5035)

**Comment by drigolin** [comment]
@huangdijia  thank you...
